ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:rootdir: .
:imagesdir: {rootdir}/images
//:numbered:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toclevels: 2
:toc:
:toc-placement!:

= arrayp

Functions for manipulating collections of JavaScript ((`Promise`)) objects.

== Usage
Install with `npm`.

```bash
$ npm install arrayp --save
```

```javascript
const arrayp = require('arrayp');

// Chain list of promises, passing result of one to the next.
arrayp.chain( [
  // Synchronously resolves to '1'
  1,

  // Argument: '1'. Asynchronously resolves to '2'
  ( x ) => new Promise( ( resolve ) =>
    setTimeout( () => resolve( x + 1 ), 250 ) ),

  // Argument: '2'. Asynchronously resolves to '6'
  ( x ) => x * 3,

  // Argument: '6'. Asynchronously resolves to '2'
  ( x ) => Promise.resolve( x - 4 ),

] ).then( console.log );

//output: 2
```

=== About arrayp Iterables
`arrayp` methods operate on JavaScript https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#The_iterable_protocol:[iterables] which can contain literals, objects or functions. Before a collection item is used, it converted to a promise. `arrayp` methods use the `Promise` objects by asynchronously waiting for an item's resolved value (or rejection error).

Collection items are converted to `Promise` objects in the following manner:

* `Promise` objects are used as-is.
* Non `Promise` objects are converted to a `Promise` that resolve to the object
* Functions are wrapped in a `Promise`. When used, the function is invoked and the `Promise` resolves with the value returned by the function, or is rejected with an error if the function throws an error.

== Methods

=== chain(iterable [, initial]) : Promise

```javascript
const {chain} = require('arrayp');
```

`chain` evaluates each promise in the iterable in series and returns a `Promise` that resolves with the value from the last item in the iterable, or rejects with the reason from the first item in the iterable that rejects. The value from one item in the iterable is passed as an argument to the next item. An optional `initial` value to the `chain` method will be passed to the first promise of the iterable.

NOTE: Passing the previous value to the next item is meaningful only when the next item is a function.

==== Parameters
* `*array*` An iterable object, such as an `Array`.
* `*initial*` `_(*)_` Optional value passed to the first item.

==== Returns
A pending `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise[Promise]` that resolves with the value of the last item of the array, or rejects with reason of the first rejecting item in the iterable.

==== Description
This method can be useful for chaining multiple promises.

.Fulfilment
* If an empty iterable is passed, this method returns (synchronously) an already resolved promise.
* In all other cases, the promise returned by `chain` is fulfilled asynchronously.

.Rejection
If an iterable item rejects, `chain` asynchronously rejects with the rejection reason. Subsequent items in the iterable are not processed.

==== Examples

```javascript
arrayp.chain( [
  1, //literal
  ( x ) => new Promise( ( resolve ) =>
    setTimeout( () => resolve( x + 1 ), 250 ) ),
  ( x ) => x * 3,
  ( x ) => Promise.resolve( x - 4 ),
] ).then( console.log );

//output: 2
```

This is equivalent to the following `Promise` chain:

```javascript
Promise
    .resolve( 1 )
    .then( ( x ) => new Promise(
      ( resolve ) => setTimeout(
        () => resolve( x + 1 ), 250 ) ) )
    .then( ( x ) => x * 3 )
    .then( ( x ) => Promise.resolve( x - 4 ) )
    .then(console.log);

//output: 2
```

=== `series(iterable)`


=== `first(array)`

```javascript
const {tryEach} = require('arrayp');
```

Runs each item of the array in series and returns a `Promise`. It stops at the first `Promise` that resolves successfully and the returned `Promise` resolves to that value. If all items in the array reject with errors, the returned `Promise` is rejected with the error returned by the final item in the series.

==== Arguments
* `*array*` `Array | Iterable` - The collection of items to execute.

==== Returns
* `*Promise*` which resolves with the value of the first successful item of the array, or rejects with the error of the last item.

==== Example

```javascript
arrayp.tryEach([
  Promise.reject('not this'),
  () => {throw new Error('not this either')},
  'this one',
  "shouldn't get here"
]).then(console.log);

//output: this one
```



=== `parallel(array [, limit])`
