ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:rootdir: .
:imagesdir: {rootdir}/images
//:numbered:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:toclevels: 2
:toc:
:toc-placement!:

= `arrayp`

`arrayp` is a utility module which provides functions for manipulating collections of JavaScript `Promise` objects.

//toc:Iu:[]

== Install
Install with `npm`.

```bash
$ npm install arrayp --save
```

== Usage
```javascript
const arrayp = require('arrayp');
```

=== About `arrayp` Collections
`arrayp` methods operate on JavaScript collections which can contain literals, objects or functions. Before a collection item is used, it converted to a promise. Methods use the `Promise` objects by asynchronously waiting for an item's result (or error). In one sense, the collection can be viewed as containing tasks which are executed by `arrayp` methods.

Collection items are converted to `Promise` objects in the following manner:

* `Promise` objects are used as-is. Methods _invoke_ the item by using the result of the `Promise`  object.
* Non `Promise` objects are converted to a `Promise` which resolves to the object (with `Promise.resolve()`). Invoking the item returns the item itself.
* Functions are wrapped in a `Promise`. When used, the function is invoked and the `Promise` resolves with the value returned by the function, or is rejected with an error if the function throws an error.

== Methods

=== `chain(iterable [, initial]) : Promise`

```javascript
const {chain} = require('arrayp');
```
The `chain` method evaluates each promise in the iterable in series and returns a `Promise` that resolves with the value from the last item in the iterable, or rejects with the reason from the first item in the iterable that rejects.

The value from one item in the iterable is passed as an argument to the next item. This is meaningful only when the next item is a function (similar to a `onFulfilled` handler of the `Promise.then()` method).

The optional `initial` value to the `chain` method will be passed to the first promise of the iterable.

==== Parameters
* `*array*` - An iterable footnote:[iterable,  The collection of items to execute.]
* `*initial*` `_(*)_` - Optional value passed to the first item.

==== Returns
* `*Promise*` which resolves with the value of the last item of the array, or rejects with the first error encountered.

```javascript
arrayp.chain( [
  1, //literal
  ( x ) => new Promise( ( resolve ) =>
    setTimeout( () => resolve( x + 1 ), 250 ) ),
  ( x ) => x * 3,
  ( x ) => Promise.resolve( x - 4 ),
] ).then( console.log );

//output: 2
```

This is equivalent to the following `Promise` chain:

```javascript
Promise
    .resolve( 1 )
    .then( ( x ) => new Promise(
      ( resolve ) => setTimeout(
        () => resolve( x + 1 ), 250 ) ) )
    .then( ( x ) => x * 3 )
    .then( ( x ) => Promise.resolve( x - 4 ) )
    .then(console.log);

//output: 2
```

=== `first(array)`

```javascript
const {tryEach} = require('arrayp');
```

Runs each item of the array in series and returns a `Promise`. It stops at the first `Promise` that resolves successfully and the returned `Promise` resolves to that value. If all items in the array reject with errors, the returned `Promise` is rejected with the error returned by the final item in the series.

==== Arguments
* `*array*` `Array | Iterable` - The collection of items to execute.

==== Returns
* `*Promise*` which resolves with the value of the first successful item of the array, or rejects with the error of the last item.

==== Example

```javascript
arrayp.tryEach([
  Promise.reject('not this'),
  () => {throw new Error('not this either')},
  'this one',
  "shouldn't get here"
]).then(console.log);

//output: this one
```


=== `series(array [, join])`

=== `waterfall(array [, join])`

=== `parallel(array [, limit])`
